project:
  type: book
  # Make sure both the light and dark images are bundled.
  resources:
    - images/*_light.svg
    - images/*_dark.svg

execute:
  freeze: auto

date-modified: last-modified

book:
  # Basic info
  title: "Practical Python Programming for Life Scientists"
  description: "Learn essential Python programming skills tailored for life science research. This practical guide helps biology and life science students with no prior coding experience develop fundamental programming and data analysis skills."
  author: "Ryan M. Moore, PhD"
  date: "2025-02-05"

  # Content
  chapters:
    - index.qmd
    - basics.qmd
    - collections.qmd
    - algorithms.qmd
    - functions.qmd
    - text: "Object-Oriented Programming"
      href: object_oriented_programming.qmd
    - errors_exceptions.qmd
    - text: "Exploratory Data Analysis"
      href: exploratory_data_analysis.qmd
    - text: "Statistics & Modeling"
      href: stats_models.qmd
    - io_files_contexts.qmd
  appendices:
    - part: Errors & Exceptions
      chapters:
        - text: Stop & Think Answers
          href: errors_exceptions/think_answers.qmd
        - text: Practice Problem Solutions
          href: errors_exceptions/practice_solutions.qmd
    - part: Exploratory Data Analysis
      chapters:
        - text: Stop & Think Answers
          href: exploratory_data_analysis/think_answers.qmd
        - text: Practice Problem Solutions
          href: exploratory_data_analysis/practice_solutions.qmd
    - part: Statistics & Modeling
      chapters:
        - text: Stop & Think Answers
          href: stats_models/think_answers.qmd
        - text: Practice Problem Solutions
          href: stats_models/practice_solutions.qmd
    - part: I/O, Files, & Contexts
      chapters:
        - text: Stop & Think Answers
          href: io_files_contexts/think_answers.qmd
        - text: Practice Problem Solutions
          href: io_files_contexts/practice_solutions.qmd
    - text: Regular Expressions
      href: regex.qmd

  # Site stuff
  cover-image: images/dna_python_logo.webp
  cover-image-alt: "DNA double helix to the left and Python logo to the right"
  sidebar:
    style: "docked"
    logo: images/dna_python_logo.webp
    logo-alt: "DNA double helix to the left and Python logo to the right"
  page-footer:
    left: "© 2025 Ryan M. Moore. CC BY 4.0."
    right:
      - icon: person-lines-fill
        href: https://orcid.org/0000-0003-3337-8184
      - icon: journals
        href: https://scholar.google.com/citations?user=W08DPpMAAAAJ
      - icon: github
        href: https://github.com/mooreryan
  open-graph: true

  # GitHub
  site-url: https://pythonforlifescientists.com
  repo-url: https://github.com/mooreryan/practical_python
  repo-branch: main
  repo-actions: [issue, source]

bibliography: references.bib

format:
  html:
    theme:
      dark: [custom.scss, darkly]
      light: [custom.scss, flatly]
      # - custom.scss
      # - flatly
    include-after-body:
      - includes/switch_images_for_theme.html
      - includes/simple_analytics.html
    # include-in-header: includes/site_verification.html
    number-depth: 1
    toc-depth: 6
  # pdf:
  #   documentclass: scrreprt
