project:
  type: book
  # Make sure both the light and dark images are bundled.
  resources:
    - images/*_light.svg
    - images/*_dark.svg

execute:
  freeze: auto

date-modified: last-modified

book:
  # Basic info
  title: "Applied Python Programming for Life Scientists: From Fundamentals to Algorithmic Thinking and Data-Driven Discovery"
  description: "A beginner-friendly Python textbook for life scientists and biologists. Learn Python programming, build problem-solving skills, develop algorithmic thinking, and apply data-driven methods to research."
  author: "Ryan M. Moore, PhD"
  date: "2025-02-05"

  # Content
  chapters:
    - index.qmd
    - basics/index.qmd
    - collections/index.qmd
    - algorithmic_thinking/index.qmd
    - understanding_functions/index.qmd
    - text: "Object-Oriented Programming"
      href: object_oriented_programming/index.qmd
    - errors_exceptions/index.qmd
    - text: "Exploratory Data Analysis"
      href: exploratory_data_analysis/index.qmd
    - text: "Statistics & Modeling"
      href: stats_models/index.qmd
    - io_files_contexts/index.qmd
  appendices:
    - part: Basics
      chapters:
        - text: Practice Problems
          href: basics/practice_problems/index.qmd
        - text: Practice Problem Solutions
          href: basics/practice_solutions/index.qmd
        # - text: Stop & Think Answers
        #   href: basics/think_answers/index.qmd
    - part: Collections
      chapters:
        - text: Practice Problems
          href: collections/practice_problems/index.qmd
        - text: Practice Problem Solutions
          href: collections/practice_solutions/index.qmd
    - part: Errors & Exceptions
      chapters:
        - text: Stop & Think Answers
          href: errors_exceptions/think_answers/index.qmd
        - text: Practice Problem Solutions
          href: errors_exceptions/practice_solutions/index.qmd
    - part: Exploratory Data Analysis
      chapters:
        - text: Stop & Think Answers
          href: exploratory_data_analysis/think_answers/index.qmd
        - text: Practice Problem Solutions
          href: exploratory_data_analysis/practice_solutions/index.qmd
    - part: Statistics & Modeling
      chapters:
        - text: Stop & Think Answers
          href: stats_models/think_answers/index.qmd
        - text: Practice Problem Solutions
          href: stats_models/practice_solutions/index.qmd
    - part: I/O, Files, & Contexts
      chapters:
        - text: Stop & Think Answers
          href: io_files_contexts/think_answers/index.qmd
        - text: Practice Problem Solutions
          href: io_files_contexts/practice_solutions/index.qmd
    - text: Regular Expressions
      href: regex/index.qmd

  # Site stuff
  cover-image: images/dna_python_logo.webp
  cover-image-alt: "DNA double helix to the left and Python logo to the right"
  sidebar:
    style: "docked"
    logo: images/dna_python_logo.webp
    logo-alt: "DNA double helix to the left and Python logo to the right"
  page-footer:
    left: "© 2025 Ryan M. Moore. CC BY 4.0."
    right:
      - icon: person-lines-fill
        href: https://orcid.org/0000-0003-3337-8184
      - icon: journals
        href: https://scholar.google.com/citations?user=W08DPpMAAAAJ
      - icon: github
        href: https://github.com/mooreryan
  open-graph: true

  # GitHub
  site-url: https://appliedpythonprogramming.com
  favicon: images/favicon.ico
  repo-url: https://github.com/mooreryan/practical_python
  repo-branch: main
  repo-actions: [issue, source]

# bibliography: references.bib

format:
  html:
    link-external-icon: true
    canonical-url: true
    theme:
      dark: [custom.scss, darkly]
      light: [custom.scss, flatly]
      # - custom.scss
      # - flatly
    include-after-body:
      - includes/switch_images_for_theme.html
      - includes/simple_analytics.html
    # include-in-header: includes/site_verification.html
    number-depth: 2
    toc-depth: 6
  # pdf:
  #   documentclass: scrreprt
