project:
  type: book

execute:
  freeze: auto

date-modified: last-modified

book:
  # Basic info
  title: "Practical Python Programming for Life Scientists"
  description: "Learn essential Python programming skills tailored for life science research. This practical guide helps biology and life science students with no prior coding experience develop fundamental programming and data analysis skills."
  author: "Ryan M. Moore, PhD"
  date: "2025-02-05"

  # Content
  chapters:
    - index.qmd
    - chapters/01_basics.qmd
    - chapters/02_collections.qmd
    - chapters/03_algorithms.qmd
    - chapters/04_functions.qmd
    - chapters/05_classes.qmd
    - chapters/06_errors.qmd
    - chapters/07_exploratory_data_analysis.qmd
    - chapters/08_stats_models.qmd
    - chapters/09_io_files_contexts.qmd
    - part: Appendices
      chapters:
        - chapters/A01_solutions.qmd
        - chapters/A02_regex.qmd

  # Site stuff
  cover-image: images/dna_python_logo.webp
  cover-image-alt: "DNA double helix to the left and Python logo to the right"
  sidebar:
    logo: images/dna_python_logo.webp
    logo-alt: "DNA double helix to the left and Python logo to the right"
  page-footer:
    left: "© 2025 Ryan M. Moore. CC BY 4.0."
    right:
      - icon: person-lines-fill
        href: https://orcid.org/0000-0003-3337-8184
      - icon: journals
        href: https://scholar.google.com/citations?user=W08DPpMAAAAJ
      - icon: github
        href: https://github.com/mooreryan
  open-graph: true

  # GitHub
  # site-url: https://www.pythonforlifescientists.com
  repo-url: https://github.com/mooreryan/practical_python
  repo-branch: main
  repo-actions: [issue, source]

bibliography: references.bib

format:
  html:
    theme:
      - custom.scss
      - cosmo
    include-after-body: includes/simple_analytics.html
    # include-in-header: includes/site_verification.html
    number-depth: 1
    toc-depth: 6
  # pdf:
  #   documentclass: scrreprt
